### ISSUE TITLE
ads Show box

### ISSUE THREAD

**Issue by isurajmehra** [KodiMadhavarao/Ipl2018#1]
bro,,, can we place ads in this app, and how to do that, i am beginner, please brother tell me

**Comment by KodiMadhavarao** [comment]
Yes you can fork this project and place ads .
But it is not production 
If you want to learn there are lot of tutorials out there .
But if you want to earn i would say **NO**  don't do that there is already official application in playstore  
The below link is for android documentation 
https://developers.google.com/admob/android/quick-start
